### PR TITLE
Allow configuration of TCP timeout while waiting for response

### PR DESCRIPTION
**Pull request by edevil**
This allows us to configure how long Unbound will wait for a response
on a TCP connection.

Related to #470

### CODE REVIEW

**Review by wcawijngaards — APPROVED** [review]
Looks good! Thanks for the additional config setting, perhaps it can help if there are connection issues with (certain types of) upstream TCP servers.

**Comment by edevil** [comment]
Resolved conflicts.

**Comment by edevil** [comment]
@wcawijngaards Do you want me to make further changes to this PR?

**Comment by wcawijngaards** [comment]
No changes are needed, I merged the patch. The features could be useful for people that want to configure tcp behaviour. Thanks for the patch!

**Pull request merged**
