### PR TITLE
Allow configuration of persistent TCP connections

### PR DESCRIPTION
**Pull request by edevil**
Added 2 new options to configure previously hardcoded
values: max-reuse-tcp-queries and tcp-reuse-timeout. These
allow fine-grained control over how unbound uses persistent
TCP connections to authority servers.

Some authority servers don't deal well with sending multiple
queries over the same TCP connection so configuring these
values is necessary.

### CODE REVIEW

**Review by wcawijngaards — APPROVED** [review]
These options look good and can be merged.

**Comment by wcawijngaards** [comment]
The code looks good so I merged it. From our discussion, an option for the auth tcp timeout would perhaps also be useful in this problem space and could be helpful for solutions.

**Comment by iz8mbw** [comment]
@edevil @wcawijngaards thanks for that!

**Comment by oerdnj** [comment]
Hi @edevil, could you please expand on:

> Some authority servers don't deal well with sending multiple queries over the same TCP connection so configuring these values is necessary.

Do you have any datapoints and can you describe the behaviour by those authoritative servers?  Either here or [dns-operations](https://lists.dns-oarc.net/mailman/listinfo/dns-operations) would be fine, I guess.

**Comment by edevil** [comment]
Hello @oerdnj

It has been a while since I looked at this, but what I was seeing at the time was that some servers did not respond to subsequent queries on the same TCP socket, but also did not close it. So this caused high latency because Unbound would first need to give up on the tcp socket before a successful query was sent.

**Comment by oerdnj** [comment]
Oh, so it was a **client** issue and not a **server** issue.  That's good to know, thank you, @edevil!

**Comment by edevil** [comment]
Well, I wouldn't consider keeping the TCP connection open and ignoring new queries on that connection a good behavior... :)

These options mitigate the issue on the client side but it seems more like a server issue.

**Pull request merged**
