### PR TITLE
When iterating, fix the timeout bug

### PR DESCRIPTION
**Pull request by ShipeiXu**
When iterating, fix the timeout bug

### CODE REVIEW

**Comment by ShipeiXu** [comment]
Question 2: Set udp socket to pass icmp host unreachable

**Comment by ShipeiXu** [comment]
https://github.com/NLnetLabs/unbound/issues/844

**Comment by wcawijngaards** [comment]
The change in the iterator code, that limits the number of timeouts that are processed, is not the intended operation. The msg retry count is used per destination, the change limits the number of attempts, realistically. This may help with making timeouts turn into servfail faster, but I see no value in that, since before the servfail conclusion there is no answer available as well.

The change that turns on RECVERR looks interesting. What does that do? I mean, what change does not make for the operation of queries? Getting better errors or have more errors reported sounds like a good idea. And this could be good to include in the code. But the code does not inspect the MSG_ERRQUEUE and thus I wonder if the feature turns out to be useful. Also on Linux hosts unreachable errors may be reported anyway, regardless of the option.

**Comment by ShipeiXu** [comment]
Your explanation makes sense, but it still doesn't match reality. In the scenario I tested (domain name fip.cscec.com), the a record of cscec-ipv6.cscec.com is an iter_qstate that can never be resolved. Its timeout far exceeds the number of outbound_msg_retry.
I try to find a more reasonable way to modify the timeout limit.
As for the RECVERR setting, it is because the udp socket of linux cannot receive the icmp host unreacable error. But even if it is received, it is indeed of no practical use. Unable to reach processQueryResponse logic.

**Comment by ShipeiXu** [comment]
you're right. But there are still some problems here. When the ip address of ns has both ipv4 and ipv6, each will be tried. Regardless of whether the dns server has an ipv6 address or not. This results in an unresolved iter_qstate with a very long timeout. A meaningful change here should be as follows:
1 Limit the total timeout times of iter_qstate; 2 Check the ipv6 address of the host (if it is local ipv6), stop trying ipv6 requests.

**Comment by ShipeiXu** [comment]
In a sub-iteration, trying 3 ip server addresses is very significant. There is no need to try them all. It's prudent though.

**Comment by TrueSEClab** [comment]
#858 Error. Compiler on windows 10 21H2 (Winver 19044.2604)  MINGW64

``` ./configure --enable-debug --disable-gost --disable-flto --enable-tfo-client --enable-static-exe --enable-dnscrypt --enable-cachedb --with-ssl --with-libevent=no --with-libexpat=/usr --with-libhiredis=/mingw64 --with-libsodium=/mingw64```

```  code
# add code:
		iq->refetch_glue = 0;
		iq->minimisation_state = DONOT_MINIMISE_STATE;
		/* the request has been forwarded.
		 * forwarded requests need to be immediately sent to the 
		 * next state, QUERYTARGETS. */
		/* return next_state(iq, QUERYTARGETS_STATE);*/
		if (iq->timeout_count >= env->cfg->outbound_msg_retry) {
		    return next_state(iq, FINISHED_STATE);
        } else {
		    return next_state(iq, QUERYTARGETS_STATE);
        }
```

> MINGW64 ~/unbound
# `make` outlog
./libtool --tag=CC --mode=compile gcc -I.  -I/mingw64/include -DSRCDIR=.  -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include  -o dns.lo -c services/cache/dns.c
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/dns.c  -DDLL_EXPORT -DPIC -o .libs/dns.o
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/dns.c -o dns.o >/dev/null 2>&1
./libtool --tag=CC --mode=compile gcc -I.  -I/mingw64/include -DSRCDIR=.  -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include  -o infra.lo -c services/cache/infra.c
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/infra.c  -DDLL_EXPORT -DPIC -o .libs/infra.o
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/infra.c -o infra.o >/dev/null 2>&1
./libtool --tag=CC --mode=compile gcc -I.  -I/mingw64/include -DSRCDIR=.  -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include  -o rrset.lo -c services/cache/rrset.c
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/rrset.c  -DDLL_EXPORT -DPIC -o .libs/rrset.o
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/rrset.c -o rrset.o >/dev/null 2>&1
./libtool --tag=CC --mode=compile gcc -I.  -I/mingw64/include -DSRCDIR=.  -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include  -o dname.lo -c util/data/dname.c
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/dname.c  -DDLL_EXPORT -DPIC -o .libs/dname.o
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/dname.c -o dname.o >/dev/null 2>&1
./libtool --tag=CC --mode=compile gcc -I.  -I/mingw64/include -DSRCDIR=.  -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include  -o msgencode.lo -c util/data/msgencode.c
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/msgencode.c  -DDLL_EXPORT -DPIC -o .libs/msgencode.o
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/msgencode.c -o msgencode.o >/dev/null 2>&1
./libtool --tag=CC --mode=compile gcc -I.  -I/mingw64/include -DSRCDIR=.  -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include  -o as112.lo -c util/as112.c
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/as112.c  -DDLL_EXPORT -DPIC -o .libs/as112.o
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/as112.c -o as112.o >/dev/null 2>&1
./libtool --tag=CC --mode=compile gcc -I.  -I/mingw64/include -DSRCDIR=.  -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include  -o msgparse.lo -c util/data/msgparse.c
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/msgparse.c  -DDLL_EXPORT -DPIC -o .libs/msgparse.o
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/msgparse.c -o msgparse.o >/dev/null 2>&1
./libtool --tag=CC --mode=compile gcc -I.  -I/mingw64/include -DSRCDIR=.  -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include  -o msgreply.lo -c util/data/msgreply.c
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/msgreply.c  -DDLL_EXPORT -DPIC -o .libs/msgreply.o
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/msgreply.c -o msgreply.o >/dev/null 2>&1
./libtool --tag=CC --mode=compile gcc -I.  -I/mingw64/include -DSRCDIR=.  -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include  -o packed_rrset.lo -c util/data/packed_rrset.c
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/packed_rrset.c  -DDLL_EXPORT -DPIC -o .libs/packed_rrset.o
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/packed_rrset.c -o packed_rrset.o >/dev/null 2>&1
./libtool --tag=CC --mode=compile gcc -I.  -I/mingw64/include -DSRCDIR=.  -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include  -o iterator.lo -c iterator/iterator.c
libtool: compile:  gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c iterator/iterator.c  -DDLL_EXPORT -DPIC -o .libs/iterator.o
iterator/iterator.c: In function 'processInitRequest':
iterator/iterator.c:1457:42: error: 'env' undeclared (first use in this function)
 1457 |                 if (iq->timeout_count >= env->cfg->outbound_msg_retry) {
      |                                          ^~~
iterator/iterator.c:1457:42: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:319: iterator.lo] Error 1`

**Comment by ShipeiXu** [comment]
> #858 Error. Compiler on windows 10 21H2 (Winver 19044.2604) MINGW64
> 
> ` ./configure --enable-debug --disable-gost --disable-flto --enable-tfo-client --enable-static-exe --enable-dnscrypt --enable-cachedb --with-ssl --with-libevent=no --with-libexpat=/usr --with-libhiredis=/mingw64 --with-libsodium=/mingw64`
> 
> ```
> # add code:
> 		iq->refetch_glue = 0;
> 		iq->minimisation_state = DONOT_MINIMISE_STATE;
> 		/* the request has been forwarded.
> 		 * forwarded requests need to be immediately sent to the 
> 		 * next state, QUERYTARGETS. */
> 		/* return next_state(iq, QUERYTARGETS_STATE);*/
> 		if (iq->timeout_count >= env->cfg->outbound_msg_retry) {
> 		    return next_state(iq, FINISHED_STATE);
>         } else {
> 		    return next_state(iq, QUERYTARGETS_STATE);
>         }
> ```
> 
> > MINGW64 ~/unbound
> 
> # `make` outlog
> ./libtool --tag=CC --mode=compile gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -o dns.lo -c services/cache/dns.c libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/dns.c -DDLL_EXPORT -DPIC -o .libs/dns.o libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/dns.c -o dns.o >/dev/null 2>&1 ./libtool --tag=CC --mode=compile gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -o infra.lo -c services/cache/infra.c libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/infra.c -DDLL_EXPORT -DPIC -o .libs/infra.o libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/infra.c -o infra.o >/dev/null 2>&1 ./libtool --tag=CC --mode=compile gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -o rrset.lo -c services/cache/rrset.c libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/rrset.c -DDLL_EXPORT -DPIC -o .libs/rrset.o libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c services/cache/rrset.c -o rrset.o >/dev/null 2>&1 ./libtool --tag=CC --mode=compile gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -o dname.lo -c util/data/dname.c libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/dname.c -DDLL_EXPORT -DPIC -o .libs/dname.o libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/dname.c -o dname.o >/dev/null 2>&1 ./libtool --tag=CC --mode=compile gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -o msgencode.lo -c util/data/msgencode.c libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/msgencode.c -DDLL_EXPORT -DPIC -o .libs/msgencode.o libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/msgencode.c -o msgencode.o >/dev/null 2>&1 ./libtool --tag=CC --mode=compile gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -o as112.lo -c util/as112.c libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/as112.c -DDLL_EXPORT -DPIC -o .libs/as112.o libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/as112.c -o as112.o >/dev/null 2>&1 ./libtool --tag=CC --mode=compile gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -o msgparse.lo -c util/data/msgparse.c libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/msgparse.c -DDLL_EXPORT -DPIC -o .libs/msgparse.o libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/msgparse.c -o msgparse.o >/dev/null 2>&1 ./libtool --tag=CC --mode=compile gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -o msgreply.lo -c util/data/msgreply.c libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/msgreply.c -DDLL_EXPORT -DPIC -o .libs/msgreply.o libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/msgreply.c -o msgreply.o >/dev/null 2>&1 ./libtool --tag=CC --mode=compile gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -o packed_rrset.lo -c util/data/packed_rrset.c libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/packed_rrset.c -DDLL_EXPORT -DPIC -o .libs/packed_rrset.o libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c util/data/packed_rrset.c -o packed_rrset.o >/dev/null 2>&1 ./libtool --tag=CC --mode=compile gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -o iterator.lo -c iterator/iterator.c libtool: compile: gcc -I. -I/mingw64/include -DSRCDIR=. -g -O2 -W -Wall -Wextra -Wdeclaration-after-statement -I/mingw64/include -c iterator/iterator.c -DDLL_EXPORT -DPIC -o .libs/iterator.o iterator/iterator.c: In function 'processInitRequest': iterator/iterator.c:1457:42: error: 'env' undeclared (first use in this function) 1457 | if (iq->timeout_count >= env->cfg->outbound_msg_retry) { | ^~~ iterator/iterator.c:1457:42: note: each undeclared identifier is reported only once for each function it appears in make: *** [Makefile:319: iterator.lo] Error 1`

The wrong code you got, there are two commits in total, take a closer look.

**Comment by ShipeiXu** [comment]
close this pr. it's not perferct

**Comment by ShipeiXu** [comment]
close this pr. it's not perferct

**Pull request closed without merging**
