### PR TITLE
Update README-Travis.md

### PR DESCRIPTION
**Pull request by noloader**
This PR updates README-Travis.md.

The first change adds section headers to the steps used in Android testing. The second change adds a few additional sections, like building the prereqs OpenSSL and Expat. Another section added is Developer Workstation, which discusses sharp edges for developers.

The PR also removes some additional legacy NDK gear from OpenSSL's 15-android.conf.

### CODE REVIEW

**Comment by ralphdolmans** [comment]
Hi, Is this PR closed on purpose? The changes seem valuable to me.

**Comment by noloader** [comment]
Hi @ralphdolmans,

It looks like it got closed automatically when I sync'd with upstream (more correctly, during the push).

I think the change should be merged.

Would you like another PR? Or can you work with this PR?

**Comment by ralphdolmans** [comment]
No problem, I can work with this PR. Thanks!

**Comment by noloader** [comment]
@ralphdolmans,

In case it helps: [README-Travis.md.zip](https://github.com/NLnetLabs/unbound/files/4286772/README-Travis.md.zip).

It has the original changes from the PR and one small update. The update is due to merging "don't call exit in Travis script" PR today.

**Comment by ralphdolmans** [comment]
Thanks again! Commited the changes to master in https://github.com/NLnetLabs/unbound/commit/cd6bb00f2c525c8d87695a45f9a9e5ef7a29683c.

**Pull request closed without merging**
