### PR TITLE
Rpz url notify issue

### LINKED ISSUE #679: allow-notify doesn't work for url on rpz zones
**Describe the bug**
Setting a `allow-notify` setting with an IP address doesn't allow Unbound receive notifications from that IP on RPZ zones.

**To reproduce**
1. Configure a config file like this:
```
server:
    module-config: "respip validator iterator"
    directory: "/usr/local/etc/unbound"
    username: unbound
    chroot: "/usr/local/etc/unbound"
    logfile: "/usr/local/etc/unbound/logs/unbound.log"
    log-time-ascii: yes
    trust-anchor-file: "/usr/local/etc/unbound/root.key"
    verbosity: 4      # get more logging.
    interface: 0.0.0.0
    extended-statistics: yes 
    access-control: 10.0.0.0/16 allow
    private-address: 10.0.0.0/16

remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    server-key-file: "/usr/local/etc/unbound/unbound_server.key"
    server-cert-file: "/usr/local/etc/unbound/unbound_server.pem"
    control-key-file: "/usr/local/etc/unbound/unbound_control.key"
    control-cert-file: "/usr/local/etc/unbound/unbound_control.pem"

forward-zone:
  name: "."
  forward-addr: 1.1.1.1

rpz:
    name: rpz.allowed.domains
    url: "https://mytest.server.com/rpz.allowed.domains"
    rpz-log: yes
    rpz-log-name: rpz-allowed-domain
    allow-notify: 10.0.0.1

rpz:
    name: rpz.blocked.domains
    url: "https://mytest.server.com/rpz.blocked.domains"
    rpz-log: yes
    rpz-log-name: rpz-blocked-domain
    allow-notify: 10.0.0.1
```
3. Use the `https://github.com/abh/dns-notify` or other tool to call NOTIFY on the VM 10.0.0.1
```
go run dns-notify.go -domain rpz.allowed.domains 10.0.0.2:53
```
5. The server will answer `not ok (REFUSED)`

**Expected behavior**

We expected it succeed and downloaded the zone file as soon as received the NOTIFY message.

**System:**
 - Unbound version: 1.15.0
 - OS: CentOS 7
 - `unbound -V` output:
```
Version 1.15.0

Configure line:
Linked libs: mini-event internal (it uses select), OpenSSL 1.0.2k-fips  26 Jan 2017
Linked modules: dns64 respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Additional information**
I added a lot of `log_err()` to realize what happen and what I could understand is if we don't have `task_probe` (no primary zone dns servers) the `auth_master` struct (xfr->allow_notify_list) never gets values from allow-notify setting and that's why unbound refuses to receive the notify.

### PR DESCRIPTION
**Pull request by Philip-NLnetLabs**
Fix for issue #679

### CODE REVIEW

**Review by gthess — APPROVED** [review]
LGTM and all tests pass locally.

**Comment by SaintBol** [comment]
With unbound 1.16.2, using
`url: http://some.IP.v.4/path/filename.stuff`
I can observe that this doesn't work and that I am still obliged to include an allow-notify line in the config for the rpz zone.

**Comment by gthess** [comment]
This should work without specifying an `allow-notify` if the IP the NOTIFY comes from is the same IP as "some.IP.v.4".
Also the qname of the NOTIFY needs to match the configured rpz zone name (I believe that is not your problem).
The testcase for this issue still works btw.

With verbosity 2 and above you would see something like the following in the log that may shed more light:
```
info: received NOTIFY for rpz. from 127.0.0.1 port 35684
info: refused NOTIFY for . from 127.0.0.1 port 34962
```

**Comment by SaintBol** [comment]
This is what I had in the config: url: http://a.b.c.d/mypath/myfile
Received a REJECT for the notify I sent from the same IP a.b.c.d.
Added an allow-notify: no error and the file was downloaded.

**Comment by gthess** [comment]
Do you mean REFUSE instead of REJECT?
Also could you post the relative unbound log entry?

**Pull request merged**
